### ISSUE TITLE
fix filter on projects-check page 

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4850]
### Dependency
- [x] #4960 
Note:  If the above issue results in the decision to adopt the proposed solution, this issue should be closed as not planned.  

### Overview
As developers we need to fix two problems with the appearance of the filters on the projects-check page.  In both cases the correct appearance can be observed on the projects page.  

### Details

1. The filters on the [projects-check webpage](https://hackforla.org/projects-check)  should appear to the left of the project cards, however they are instead center-aligned and the project cards appear below the filters.  For the correct appearance see the [projects webpage](https://hackforla.org/projects)  or the screenshot of the projects page below under Resources.   
2. On the projects-check page, on page load, the number of displayed filters is correctly limited to eight, however no "View All" link is displayed even if more than eight filters exist.  For the correct appearance see the [projects webpage](https://hackforla.org/projects)  or the screenshot of the projects page below under Resources.   
3. On the projects-check page, the heading `Applied Filters` is missing and the filter tags representing the applied filters are displayed at the bottom of the filter list.  For the correct appearance see the [projects webpage](https://hackforla.org/projects)  or the screenshot of the projects page below under Resources.   
4. The specific filters displayed on projects-check will differ from those displayed on the projects page.  This difference is intentional and allows for the projects-check page to be used for testing, as described in #2502 
5. Note that if more than 8 categores exist in both the Technology and Language groups, it should be possible to view all the filters in both groups at once.  

### Action Items
- [ ] Update the HTML include file `_includes/current-projects-check.html` and JavaScript code file `assets/js/current-projects-check.js` so that the unintentional differences between projects-check and project pages described above are resolved, while maintaining the intended differences in the filters.  

### Resources/Instructions
<details><summary>Appearance of filters (incorrect) on Projects-check page</summary>

![image](https://github.com/hackforla/website/assets/5314153/01d37427-6152-4b7c-8070-9b5b3254e5e0)

</details> 

<details><summary>Appearance of filters (correct) on Projects Page</summary>

![image](https://github.com/hackforla/website/assets/5314153/82b8d68c-bcda-4d52-b52d-c88ee197be69)

</details> 

- Projects Check page: [Webpage](https://hackforla.org/projects-check) | [HTML include](https://github.com/hackforla/website/blob/gh-pages/_includes/current-projects-check.htthe ml) | [JavaScript](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects-check.js)
- Projects page: [Webpage](https://hackforla.org/projects.html) | [HTML include](https://github.com/hackforla/website/blob/gh-pages/_includes/current-projects.html) | [JavaScript](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
- HTML for the filters on projects page can be found in [current-projects.html] 
- This issue was created from #4834

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I moved this into the new issue review column because the dependency is resolved. Please add a ready for prioritization label if its ready.

**Comment by roslynwythe** [comment]
I don't believe this issue is still required, because as a result of #4960, the projects-check page now shares code with the projects page, with the exception of the filter groups.

**Comment by ExperimentsInHonesty** [comment]
I have verified that the projects-check page is now working as intended.  I am assuming it is due to them sharing the underlying code now.  So I closing this issue as unplanned as suggested by @roslynwythe
