### ISSUE TITLE
Customize PR instructions based on files in the PR

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5182]
### Dependency
- [x] #5165 

### Overview
We need to customize the pr instructions message.  If a PR contains multiple files including CONTRIBUTING.md, the current pr instructions are appropriate.  If CONTRIBUTING.md is the only file modified, the instructions for pulling down the issue branch locally can be omitted, and if CONTRIBUTING.md is not  modified, the instruction to preview CONTRIBUTING.md on GitHub can be omitted.  

### Action Items
- [x] Become familiar with the resources describing the HfLA GHA archtecture[^1] and testing procedures[^2] as well as the resource describing the PR Instructions GHA[^3]
- [x] Update create-instruction.js[^7] so that it examines the files changed in the PR.  
- [x] Change the implementation so that the special instruction for reviewing CONTRIBUTING.md is provided only if the PR includes a change to CONTRIBUTING.md.  
- [x] If the only file changed in the PR is CONTRIBUTING.md, then do not display the PR instruction that provides git commands pulling down the issue branch locally.  

### Resources/Instructions
[^1]:[Hack for LA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)
[^2]:[HfLA GitHub Actions](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions)
[^3]:[GHA: pr instructions](https://github.com/hackforla/website/wiki/GHA:-pr-instructions)
[^4]:[PR Instructions Template](https://github.com/hackforla/website/blob/gh-pages/github-actions/pr-instructions/pr-instructions-template.md)
[^5]:[PR Instructions Workflow](https://github.com/hackforla/website/blob/gh-pages/github-actions/pr-instructions/post-comment.js)
[^6]:[WR PR Instructions Workflow](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/wr-pr-instructions.yml)
[^7]: https://github.com/hackforla/website/blob/gh-pages/github-actions/pr-instructions/create-instruction.js
[^8]:https://github.com/hackforla/website/blob/gh-pages/github-actions/pr-instructions/post-comment.js

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I moved this into the new issue review column because the dependency is resolved.  Please add a ready for prioritization label if its ready.

**Comment by elliot-d-kim** [comment]
@roslynwythe I see that you're assigned to this issue but this issue is still in the prioritized backlog -- should I move down the backlog to work on the next issue?

**Comment by elliot-d-kim** [comment]
- Availability: Mon-Thu outside of 2-7pm, Fri before 2pm, Sat all day
- ETA: 3/5/24 (1.5 weeks)

**Comment by ExperimentsInHonesty** [comment]
@elliot-d-kim I have moved this to the inprogress column.  Next time you assign an issue, please don't forget to move it.

**Comment by elliot-d-kim** [comment]
Update: Reviewing medium PR took longer than expected, but now completed. Revised ETA below.

- Availability: Mon-Thu outside of 2-7pm, Fri before 2pm, Sat all day
- ETA: 3/17/24

**Comment by elliot-d-kim** [comment]
Taking this issue off my plate so someone else can get the chance to work on it!

Removed myself from 'Assignees' and moved issue back to Prioritized Backlog.

**Comment by anthonypz** [comment]
Availability: M-F 4-8 p.m.
ETA: end of day Saturday April 20th

**Comment by anthonypz** [comment]
There are a few errors with the code in my PR (#6685). Here's my updated ETA:

Availability: M-F 4-8 p.m.
ETA: Thursday April 25th
